### ISSUE TITLE
Menu item is disabled

### ISSUE THREAD

**Issue by marcelofabri** [bhargavg/EmojifySourceEditorExtension#1] opened 2016-06-14 21:51 UTC
I followed the steps in README, but the menu item "Emojify" is disabled (even after selecting text). Any ideas? I'm using El Capitan.

**Comment by bhargavg** [comment] 2016-06-15 04:33
The feature is buggy right now. Try cleaning the derived data and running the extension scheme again. For me it started working from second run.

**Comment by Headmast** [comment] 2016-06-18 04:53
I have the same problem, but restart doesn't help. Others extensions work correct.

**Comment by bhargavg** [comment] 2016-06-18 06:36
@Headmast Other extensions? You mean other Source Editor Extensions?

Can you see `Emojify` item in `Editor` menu?

**Comment by Headmast** [comment] 2016-06-20 06:12
Yes, I see `Emojify`, but it's disable.  [GenerateSwiftInit](https://github.com/bkobilansky/GenerateSwiftInit) and [XcodeSourceEditorExtension-Alignment](https://github.com/tid-kijyun/XcodeSourceEditorExtension-Alignment) work correct.

**Comment by bhargavg** [comment] 2016-06-20 06:22
Please make sure you've done the following:
1. Completely cleaned `DerivedData` folder.
2. Restarted Xcode - beta.
3. Signed both the extension and host app.

Also, could you please check if the extension is attached or still in `Waiting to Attach` state in Debug View?

**Comment by Headmast** [comment] 2016-06-21 05:55
I try all, nothing helped.
![2016-06-21 08 52 34](https://cloud.githubusercontent.com/assets/8297666/16219291/eebfbfe4-378d-11e6-8227-b7892404f29b.png)

**Comment by bhargavg** [comment] 2016-06-21 12:34
I'm not sure what might be the reason. Its working for me and I've even tried on other systems as well.

**Comment by bhargavg** [comment] 2016-08-10 15:18
Closing as I can't reproduce this issue.

**Closed as completed by bhargavg** 2016-08-10 15:18 UTC
